/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardShipmentsIndexRouteImport } from './routes/_authenticated/dashboard.shipments.index'
import { Route as AuthenticatedDashboardShipmentsIdRouteImport } from './routes/_authenticated/dashboard.shipments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardShipmentsIndexRoute =
  AuthenticatedDashboardShipmentsIndexRouteImport.update({
    id: '/dashboard/shipments/',
    path: '/dashboard/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardShipmentsIdRoute =
  AuthenticatedDashboardShipmentsIdRouteImport.update({
    id: '/dashboard/shipments/$id',
    path: '/dashboard/shipments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentsIdRoute
  '/dashboard/shipments/': typeof AuthenticatedDashboardShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentsIdRoute
  '/dashboard/shipments': typeof AuthenticatedDashboardShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentsIdRoute
  '/_authenticated/dashboard/shipments/': typeof AuthenticatedDashboardShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/quote'
    | '/services'
    | '/track'
    | '/dashboard/'
    | '/dashboard/shipments/$id'
    | '/dashboard/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quote'
    | '/services'
    | '/track'
    | '/dashboard'
    | '/dashboard/shipments/$id'
    | '/dashboard/shipments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/quote'
    | '/services'
    | '/track'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/shipments/$id'
    | '/_authenticated/dashboard/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/shipments/': {
      id: '/_authenticated/dashboard/shipments/'
      path: '/dashboard/shipments'
      fullPath: '/dashboard/shipments/'
      preLoaderRoute: typeof AuthenticatedDashboardShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/shipments/$id': {
      id: '/_authenticated/dashboard/shipments/$id'
      path: '/dashboard/shipments/$id'
      fullPath: '/dashboard/shipments/$id'
      preLoaderRoute: typeof AuthenticatedDashboardShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardShipmentsIdRoute: typeof AuthenticatedDashboardShipmentsIdRoute
  AuthenticatedDashboardShipmentsIndexRoute: typeof AuthenticatedDashboardShipmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardShipmentsIdRoute:
    AuthenticatedDashboardShipmentsIdRoute,
  AuthenticatedDashboardShipmentsIndexRoute:
    AuthenticatedDashboardShipmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
