import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Package, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PortalShell, PortalHeading, StatCard } from "@/components/portal-shell";

export const Route = createFileRoute("/_authenticated/admin/customers")({ component: Customers });
const nav=[{to:"/admin",label:"Overview",icon:Users,exact:true},{to:"/admin/shipments",label:"Shipments",icon:Package},{to:"/admin/customers",label:"Customers",icon:Users},{to:"/admin/tracking",label:"Tracking",icon:Package},{to:"/dashboard",label:"Customer portal",icon:Package}];
function Customers(){const q=useQuery({queryKey:["admin-customers"],queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("id,full_name,company,phone,created_at").order("created_at",{ascending:false});if(error)throw error;const {data:u}=await supabase.auth.getUser();return {profiles:data??[],email:u.user?.email}});return <PortalShell kind="Admin console" email={q.data?.email} nav={nav}><PortalHeading title="Customers" subtitle="Registered accounts and their profile information."/><div className="mt-6 grid gap-px bg-border sm:grid-cols-2"><StatCard label="Accounts" value={q.data?.profiles.length??0}/><StatCard label="Access model" value="All authenticated" hint="Every signed-in account can use admin."/></div><div className="mt-6 overflow-x-auto border border-border"><table className="w-full min-w-[650px] text-left"><thead className="border-b border-border bg-card"><tr>{["Name","Company","Phone","Created"].map(h=><th key={h} className="px-4 py-3 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">{h}</th>)}</tr></thead><tbody>{q.data?.profiles.map(p=><tr key={p.id} className="border-b border-border last:border-0"><td className="px-4 py-4 text-sm">{p.full_name??"Unnamed"}</td><td className="px-4 py-4 text-sm">{p.company??"—"}</td><td className="px-4 py-4 text-sm">{p.phone??"—"}</td><td className="px-4 py-4 text-sm">{new Date(p.created_at).toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div></PortalShell>}
